/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pluralsight;
import java.awt.Component;
import java.text.DecimalFormat;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.text.Document;
/**
 *
 * @author CBriggs
 */
public class travelAuthRequestGUI extends javax.swing.JFrame {

    private static double globalSub;
    private static double globalTotal;

    /**
     * Creates new form travelAuthRequestGUI
     */
    public travelAuthRequestGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group1 = new javax.swing.ButtonGroup();
        travelerName = new javax.swing.JTextField();
        travelerLabel = new javax.swing.JLabel();
        airfareLabel = new javax.swing.JLabel();
        foodLabel = new javax.swing.JLabel();
        hotelLabel = new javax.swing.JLabel();
        carLabel = new javax.swing.JLabel();
        shuttleLabel = new javax.swing.JLabel();
        airfareCost = new javax.swing.JTextField();
        foodCost = new javax.swing.JTextField();
        hotelCost = new javax.swing.JTextField();
        carCost = new javax.swing.JTextField();
        shuttleCost = new javax.swing.JTextField();
        calcButton = new javax.swing.JButton();
        summaryLabel = new javax.swing.JLabel();
        displayLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        locationBox = new javax.swing.JComboBox<>();
        CarCompany1 = new javax.swing.JRadioButton();
        CarCompany2 = new javax.swing.JRadioButton();
        CarCompany3 = new javax.swing.JRadioButton();
        CarCompanyLabel = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel Authorization Request");

        travelerLabel.setText("Traveler Name");

        airfareLabel.setText("Airfare Cost");

        foodLabel.setText("Food Cost");

        hotelLabel.setText("Hotel Cost");

        carLabel.setText("Car Cost");

        shuttleLabel.setText("Shuttle Cost");
        shuttleLabel.setToolTipText("");

        calcButton.setText("Calculate");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        summaryLabel.setText("Summary");

        locationLabel.setText("Location");

        locationBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City", "New York", "Miami", "Boston", "Chicago", "Los Angeles", " " }));
        locationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationBoxActionPerformed(evt);
            }
        });

        group1.add(CarCompany1);
        CarCompany1.setText("Hertz");

        group1.add(CarCompany2);
        CarCompany2.setText("Budget");

        group1.add(CarCompany3);
        CarCompany3.setText("Avis");

        CarCompanyLabel.setText("Select a Car Rental Company ");

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayLabel)
                            .addComponent(summaryLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shuttleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(carLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hotelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(foodLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(airfareLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(travelerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(locationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(calcButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(69, 69, 69)
                                        .addComponent(helpButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hotelCost)
                                        .addGap(41, 41, 41)
                                        .addComponent(CarCompanyLabel))
                                    .addComponent(foodCost)
                                    .addComponent(airfareCost)
                                    .addComponent(travelerName)
                                    .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carCost)
                                    .addComponent(shuttleCost))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CarCompany1)
                                    .addComponent(CarCompany2)
                                    .addComponent(CarCompany3))
                                .addGap(58, 58, 58)))))
                .addGap(99, 99, 99))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {airfareCost, calcButton, carCost, foodCost, hotelCost, shuttleCost, travelerName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {airfareLabel, carLabel, foodLabel, hotelLabel, shuttleLabel, travelerLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(travelerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(travelerLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationLabel)
                            .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(summaryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(displayLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(hotelLabel))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(airfareCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(airfareLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(foodCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(foodLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(hotelCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CarCompanyLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(carLabel)
                        .addComponent(carCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CarCompany1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarCompany2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(shuttleCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(shuttleLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarCompany3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcButton)
                    .addComponent(helpButton))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        // TODO add your handling code here:
        //get user input
        DecimalFormat df = new DecimalFormat("#.##");
        String inputName = travelerName.getText();
        double inputAirfare = 0;
        double inputFood = 0;
        double inputHotel = 0;
        double inputCar = 0;
        double inputShuttle = 0;
        
        try {
            inputAirfare = Double.parseDouble(airfareCost.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter A Valid Number for Airfare", "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            inputFood = Double.parseDouble(foodCost.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter A Valid Number for Food Cost", "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            inputHotel = Double.parseDouble(hotelCost.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter A Valid Number Hotel Cost", "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            inputCar = Double.parseDouble(carCost.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter A Valid Number for Car Cost", "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            inputShuttle = Double.parseDouble(shuttleCost.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Please Enter A Valid Number for Shuttle Cost", "Error", JOptionPane.ERROR_MESSAGE);
        }
            double subTotal = inputAirfare + inputFood + inputHotel + inputCar + inputShuttle;
            travelAuthRequestGUI.globalSub = subTotal;
            displayLabel.setText("Traveler Name: " + inputName + "\n Airfare Cost: " + Double.toString(inputAirfare) + "\n Food Cost: " + Double.toString(inputFood) + "\n Hotel Cost: " + Double.toString(inputHotel) + "\n Car Cost: " + Double.toString(inputCar) + "\n Shutlle Cost: " + Double.toString(inputShuttle) + "\n Trip Total: " + Double.toString(travelAuthRequestGUI.globalTotal));
    }//GEN-LAST:event_calcButtonActionPerformed
      
    private void calculate(){
        double total = travelAuthRequestGUI.globalSub + (travelAuthRequestGUI.globalSub * .10);
        travelAuthRequestGUI.globalTotal = total;
    }      
    
    private void locationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationBoxActionPerformed
        String selection;
        selection = locationBox.getSelectedItem().toString();
        System.out.println(selection);
        
        if (selection.equals("New York")) {
            foodCost.setText("70");
        } else if (selection.equals("Miami")) {
            foodCost.setText("80");
        } else if (selection.equals("Boston")) {
            foodCost.setText("85");
        } else if (selection.equals("Chicago")) {
            foodCost.setText("90");
        } else if (selection.equals("Los Angeles")) {
            foodCost.setText("95");
        }
                
         
    }//GEN-LAST:event_locationBoxActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        JFrame helpFrame = new JFrame();
        helpFrame.setVisible(true);
        helpFrame.setSize(640, 480);
        
        JTextArea helpText = new JTextArea();
        helpText.setText("This Program is intended to help customers caluclate \n how much money they need to budget for a trip.\n  Aside from entering the travelers name, you also enter airfare cost, food costs are calculated \nwhen you select a city, You will also enter hotel costs and shuttle costs.  \nThe program will calculate your trip cost from there.");
        helpText.setEditable(false);        
        helpFrame.add(helpText);
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(travelAuthRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(travelAuthRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(travelAuthRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(travelAuthRequestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new travelAuthRequestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CarCompany1;
    private javax.swing.JRadioButton CarCompany2;
    private javax.swing.JRadioButton CarCompany3;
    private javax.swing.JLabel CarCompanyLabel;
    private javax.swing.JTextField airfareCost;
    private javax.swing.JLabel airfareLabel;
    private javax.swing.JButton calcButton;
    private javax.swing.JTextField carCost;
    private javax.swing.JLabel carLabel;
    private javax.swing.JLabel displayLabel;
    private javax.swing.JTextField foodCost;
    private javax.swing.JLabel foodLabel;
    private javax.swing.ButtonGroup group1;
    private javax.swing.JButton helpButton;
    private javax.swing.JTextField hotelCost;
    private javax.swing.JLabel hotelLabel;
    private javax.swing.JComboBox<String> locationBox;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField shuttleCost;
    private javax.swing.JLabel shuttleLabel;
    private javax.swing.JLabel summaryLabel;
    private javax.swing.JLabel travelerLabel;
    private javax.swing.JTextField travelerName;
    // End of variables declaration//GEN-END:variables

    private class locationBox {

        public locationBox() {
        }
    }
}
